describe('student', () => {
  it('should redirect back', () => {
    cy.visit('/').wait(1000)
  })
  it('export card + info', () => {
    cy.visit('/students').wait(3000)
    cy.dataGridSearch('students', 'NAK VANNA')
    cy.wait(1000)
    cy.dataGridSelectRow('students')
    cy.get('button#export').click()
    cy.selectSetting('study-year-id', '២០២០-២០២១', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a7')
    cy.selectSetting('service-id', 'ថ្នាក់ទី១២', '712b6306-da69-4f56-9802-0a19efa5dc7f')
    cy.selectSetting('service-detail-id', '12 ក', '8549ce78-70b7-4188-989b-367efbad967b')
    cy.intercept('POST', 'http://127.0.0.1:4000/gql').as('exportRequest')

    cy.dataTestId('export-button').click()
    cy.wait(200)
    cy.dataTestId('student-card').click()
    cy.wait(200)
    cy.dataTestId('student-card-66x97').click()
    cy.wait('@exportRequest')
    cy.wait(200)
    cy.submitAssertSuccessful('បាននាំចេញជោគជ័យ')
    cy.wait(1000)

    cy.dataTestId('export-button').click()
    cy.wait(200)
    cy.dataTestId('student-card').click()
    cy.wait(200)
    cy.dataTestId('student-card-54x85').click()
    cy.wait('@exportRequest')
    cy.wait(200)
    cy.submitAssertSuccessful('បាននាំចេញជោគជ័យ')
    cy.wait(1000)

    cy.dataTestId('export-button').click()
    cy.wait(200)
    cy.dataTestId('new-student-info').click()
    cy.wait('@exportRequest')
    cy.wait(200)
    cy.submitAssertSuccessful('បាននាំចេញជោគជ័យ')
    cy.wait(1000)
  })
})
