describe('Working with student-enrollments feature by Tester Role', () => {
  it('should redirect back', () => {
    cy.visit('/').wait(1000)
  })
  it('should set current-study-year', () => {
    cy.visit('students/enrollments/current-study-year').wait(3000)
    cy.selectSetting('source-study-year', '២០១៩', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a6')
      .submitAssertSuccessful('រក្សាទុកបានជោគជ័យ')
      .wait(2000)
    cy.selectSetting('destination-study-year', '២០២០', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a7')
      .submitAssertSuccessful('រក្សាទុកបានជោគជ័យ')
      .wait(2000)
  })
  it('should create,list, edit and update enrollments setting', () => {
    cy.visit('/students/enrollments/setting').wait(3000)

    cy.openCreateModal()
    cy.dataTestId('name').type('២០១៩-២០២០ ទៅ ២០២០-២០២១')
    cy.selectSetting('sourceStudyYearId', '២០១៩', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a6')
    cy.selectSetting('destinationStudyYearId', '២០២០', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a7')
    cy.dateRangPicker(4)
    cy.selectSetting('source-subject-grouping-dropdown-0', 'ថ្នាក់ទី', 'fa96241b-4668-4683-b704-1e9dc098b5fb')
    cy.selectSetting('source-service-detail-dropdown-0', '11', '42fbb81d-5406-4394-9a32-fb37626775d1')
    cy.dataTestId('add-source-btn').click()
    cy.selectSetting('source-service-detail-dropdown-1', '11', 'd69331a8-8f22-414b-a8a0-d3e68cc476e6')
    cy.dataTestId('add-source-btn').click()
    cy.selectSetting('source-service-detail-dropdown-2', '11', 'e116c860-15e8-48a6-a4ba-85751fffbb83')

    cy.selectSetting('destination-subject-grouping-dropdown-0', 'ថ្នាក់ទី', 'bcf98099-454b-4bb9-933c-c9bb9c267ac5')
    cy.selectSetting('destination-service-detail-dropdown-0', '12', '96770d03-764c-4167-adeb-011a025c0c53')
    cy.selectSetting('destination-building-room-dropdown-0', 'A', '36e280d0-375a-47b0-95a4-990058b388c2')
    cy.dataTestId('destination-max-seat-0').type('35')
    cy.dataTestId('add-destination-btn').click()

    cy.selectSetting('destination-service-detail-dropdown-1', '12', 'fd7f416c-081c-44ab-ac85-6bad7732802b')
    cy.selectSetting('destination-building-room-dropdown-1', 'B', 'faf7cd63-191d-4066-a950-49cb50b1b6cf')
    cy.dataTestId('destination-max-seat-1').type('35')
    cy.submitForm()
      .submitAssertSuccessful('បន្ថែមបានជោគជ័យ')
    cy.closeModal()
    cy.wait(2000)

    cy.dataGridSearch('enrollment-setting', '២០១៩-២០២០ ទៅ ២០២០-២០២១')

    cy.get('#grid-enrollment-setting').should('be.visible')
    cy.get('#grid-enrollment-setting_content_table')
      .contains('tbody .e-row', '២០១៩-២០២០ ទៅ ២០២០-២០២១')
      .contains('tbody .e-row', '២០១៩-២០២០')
      .contains('tbody .e-row', '២០២០-២០២១')
      .should('exist')
    cy.dataGridSelectRow('enrollment-setting')
    cy.wait(1000)
    cy.openEditModal()

    cy.dataTestId('name').type(' កែប្រែ')
    cy.selectSetting('sourceStudyYearId', '២០១៩', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a6')
    cy.selectSetting('destinationStudyYearId', '២០២០', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a7')
    cy.dateRangPicker(5)
    cy.selectSetting('source-service-detail-dropdown-1', '11', '1ff1b1f2-a6ff-4ec1-86b3-32028d78bacf')
    cy.dataTestId('remove-source-detail-2').click().wait(300)

    cy.selectSetting('destination-service-detail-dropdown-0', '12', 'fa2ce867-54d5-4b48-9ddb-bfb5b4b1c9e0')
    cy.dataTestId('destination-max-seat-0').clear().type('40')
    cy.dataTestId('remove-destination-detail-1').click().wait(300)
    cy.submitForm()
      .submitAssertSuccessful('កែប្រែបានជោគជ័យ')
    cy.closeModal()
    cy.wait(2000)
    // End of EnrollmentSetting

    cy.get('a[href="/students/enrollments"]').click()
    cy.wait(2000)
    cy.openCreateModal()
    cy.selectSetting('state', 'រង់', 'pending_enrollment_state_type')
    cy.selectSetting('source-study-year-id', '២០១៩', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a6')
    cy.selectSetting('destination-study-year-id', '២០២០', 'b1a7d0b6-8eb6-452a-932f-69e09e5338a7')
    cy.selectSetting('building-room-seat-id', '5C', '3e4c9318-30b0-44b5-b330-93de538b4193')
    cy.selectSettingByIndex('student-service-id', 'សម្រាប់តេស្ដចុះឈ្មោះ', 0)
    cy.get(':nth-child(6) > :nth-child(1) > .mt-1 > .e-input-group').click().wait(1000)
    cy.get('.e-list-parent .e-list-item').first().click().wait(300)
    cy.dataTestId('student-email-0').clear().type('example@gmail.com')
    cy.dataTestId('student-facebook-0').clear().type('Pozz Lonely')
    cy.dataTestId('student-line-id-0').clear().type('pozzlonely')

    cy.dataTestId('add-address').click().wait(300)
    cy.selectSetting('address-type-0', 'ទ', 'current_address_type')
    cy.selectSetting('address-village-id-0', 'ប៉ោយប៉ែត', 'd30f4afd-fa5e-4e64-ac83-76907426add5')
    cy.selectSetting('address-type-1', 'ទ', 'pob_address_type')
    cy.selectSetting('address-village-id-1', 'បវេល', 'cc11788c-2b9b-416b-8ca5-3cf7bb5fd63a')

    cy.dataTestId('add-parent').click().wait(300)
    cy.selectSetting('parent-type-0', 'ម្ដាយ', 'mother_parent_type')
    cy.dataTestId('parent-name-0').type('ស្រី ស្អាត')
    cy.dataTestId('parent-latin-0').type('Cute Girl')
    cy.selectSetting('parent-job-0', 'លក', 'seller_job_type')
    cy.dataTestId('parent-tel-0').type('0987654321')

    cy.dataTestId('add-parent').click().wait(300)
    cy.selectSetting('parent-type-1', 'ឪពុក', 'father_parent_type')
    cy.dataTestId('parent-name-1').type('ប្រុស សង្ហា')
    cy.dataTestId('parent-latin-1').type('Handsome Boy')
    cy.selectSetting('parent-job-1', 'គ្រូ', 'teacher_job_type')
    cy.dataTestId('parent-tel-1').type('0123456789')

    // Alias waiting for request open file manager
    cy.intercept('POST', '**/api/AmazonS3Provider/AmazonS3FileOperations').as('amazonS3Request')

    cy.dataTestId('attachment-0')
      .click()
      .wait('@amazonS3Request')
    cy.wait(1000)
    // Alias for next time
    cy.contains('li.e-list-item', 'Test Folder').as('openTestFolder')

    // Open test folder
    cy.get('@openTestFolder')
      .dblclick()
      .wait('@amazonS3Request')

    cy.contains('div.e-text-content', 'test-img.jpg')
      .rightclick()
      .wait(500)

    cy.contains('li.e-menu-item', 'Choose')
      .click()
      .wait(1000)
    cy.closeModalX()
    cy.dataTestId('attachment-note-0').type('ABA KHQR')
    cy.dataTestId('add-attachment').click().wait(300)

    cy.dataTestId('attachment-1')
      .click()
      .wait('@amazonS3Request')
    cy.wait(1000)

    // Open test folder
    cy.get('@openTestFolder')
      .dblclick()
      .wait('@amazonS3Request')

    cy.contains('div.e-text-content', 'Testing.docx')
      .rightclick()
      .wait(500)

    cy.contains('li.e-menu-item', 'Choose')
      .click()
      .wait(1000)
    cy.closeModalX()
    cy.dataTestId('attachment-note-1').type('Cash on hand')
    cy.wait(1000)
    cy.submitForm()
      .submitAssertSuccessful('បន្ថែមបានជោគជ័យ')
    cy.closeModal()
    cy.wait(2000)
    cy.dataGridSearch('enrollment', 'សម្រាប់តេស្ដចុះឈ្មោះ')
    cy.dataGridSelectRow('enrollment')
    cy.openEditModal()
    cy.selectSetting('state', 'បាន', 'processed_enrollment_state_type')
    cy.dataTestId('student-email-0').type('update')
    cy.dataTestId('student-facebook-0').type(' Update')
    cy.dataTestId('student-line-id-0').type('update')

    cy.dataTestId('address-trash-1').click().wait(300)
    cy.selectSetting('address-type-0', 'ទ', 'current_address_type')
    cy.selectSetting('address-village-id-0', 'រំចេក ៥', '6efdce61-6c37-476e-9256-6a649f1e4917')

    cy.dataTestId('parent-trash-1').click().wait(300)

    cy.dataTestId('attachment-trash-1').click().wait(300)

    cy.dataTestId('attachment-0')
      .click()
      .wait('@amazonS3Request')
    cy.wait(1000)

    // Open test folder
    cy.get('@openTestFolder')
      .dblclick()
      .wait('@amazonS3Request')

    cy.contains('div.e-text-content', 'test-dog.jpeg')
      .rightclick()
      .wait(500)

    cy.contains('li.e-menu-item', 'Choose')
      .click()
      .wait(1000)
    cy.closeModalX()
    cy.dataTestId('attachment-note-0').clear().type('Due')
    cy.wait(1000)
    cy.submitForm()
      .submitAssertSuccessful('កែប្រែបានជោគជ័យ')
    cy.closeModal()
  })
})
