<script setup lang="ts">
const store = useStudentScoreStore()
onUnmounted(() => store.setGrid(null))
</script>

<template>
  <div>
    <EjsGrid
      v-bind="objectMemoize(store.gridConfig())"
      id="grid-student-scores"
      :ref="store.setGrid"
      :toolbar="store.gridToolbar"
      :row-selected="store.handleRowSelect"
      :row-deselected="store.handleRowDeselect"
    >
      <EColumns>
        <EColumn
          type="checkbox"
          width="40"
        />
        <EColumn
          field="id"
          :is-primary-key="true"
          :visible="false"
          header-text=""
          text-align="Left"
          :auto-fit="true"
          :allow-searching="false"
        />
        <EColumn
          field="studyYear.value"
          header-text="ឆ្នាំសិក្សា"
          text-align="Left"
          :auto-fit="true"
        />
        <EColumn
          field="gpa"
          header-text="GPA"
          text-align="Left"
          type="number"
          :auto-fit="true"
          :allow-searching="false"
        />
        <EColumn
          field="note"
          header-text="សំគាល់"
          text-align="Left"
          :auto-fit="true"
        />
        <EColumn
          field="insertedAt"
          header-text="បង្កើតនៅ"
          text-align="Left"
          type="date"
          format="dd/MM/yyyy hh:mm a"
          :auto-fit="true"
          :allow-searching="false"
        />
      </EColumns>
    </EjsGrid>
  </div>
</template>
