describe('Working with users feature by Tester Role', () => {
  it('should redirect back', () => {
    cy.visit('/').wait(1000)
  })
  it('should list', () => {
    cy.visit('/user-managements/users')
    cy.wait(1000)
    cy.get('#grid-users').should('be.visible')
    cy.dataGridSearch('users', 'nakvanna')
    cy.get('#grid-users_content_table')
      .contains('tbody .e-row', 'nakvannamcu@gmail.com')
      .should('exist')
  })
  it('should search and edit with users feature', () => {
    cy.visit('/en/user-managements/users')
    cy.wait(1000)
    cy.dataGridSearch('users', 'nakvanna')
    cy.dataGridSelectRow('users')
    cy.openEditModal()
    cy.dataTestId('active-checkbox').click()
    cy.dataTestId('first-name-input-field').type(' Update', { delay: 20 })
    cy.selectSetting('bucket-select-field', 'pks-nas', 'pks_nas_s3_bucket_type')
    cy.dataTestId('bucket-folder-select-field')
      .parent()
      .click()
      .wait(1000)
    cy.get('input.e-input-filter.e-input.e-lib.e-keyboard')
      .type('administrator', { delay: 20 })
    cy.get(`li.e-item-focus`)
      .click()
      .wait(1000)
    cy.dataTestId('add-user-role-btn').click()
    cy.selectSetting('user-roles.0.role-id', 'level', '622cedc7-fd75-4b1d-b70a-61b694c8b1e9')
    cy.dataTestId('add-user-role-btn').click()
    cy.selectSetting('user-roles.1.role-id', 'level', 'ebf62dcc-cd20-4cfb-9eeb-f34070b0c3af')
    cy.submitForm()
    cy.closeModal()
  })
})
