<script setup lang="ts">
const store = useParentStore()
onUnmounted(() => store.setGrid(null))
</script>

<template>
  <EjsGrid
    v-bind="objectMemoize(store.gridConfig())"
    id="grid-parents"
    :ref="store.setGrid"
    :toolbar="store.gridToolbar"
    :row-selected="store.handleRowSelect"
    :row-deselected="store.handleRowDeselect"
  >
    <EColumns>
      <EColumn
        type="checkbox"
        width="40"
      />
      <EColumn
        field="id"
        :is-primary-key="true"
        :visible="false"
        header-text=""
        text-align="Left"
        :auto-fit="true"
        :allow-searching="false"
      />
      <EColumn
        field="name"
        header-text="គោត្តនាម-នាម"
        text-align="Left"
        :auto-fit="true"
      />
      <EColumn
        field="latin"
        header-text="គោត្តនាម-នាមឡាតាំង"
        text-align="Left"
        :auto-fit="true"
      />
      <EColumn
        field="localizedType"
        header-text="ប្រភេទ"
        text-align="Left"
        :auto-fit="true"
      />
      <EColumn
        field="localizedJob"
        header-text="មុខរបរ"
        text-align="Left"
        :auto-fit="true"
      />
      <EColumn
        field="tel"
        header-text="លេខទូរស័ព្ទ"
        text-align="Left"
        :auto-fit="true"
      />
      <EColumn
        field="insertedAt"
        header-text="បង្កើតនៅ"
        text-align="Left"
        type="date"
        format="dd/MM/yyyy hh:mm a"
        :auto-fit="true"
        :allow-filtering="false"
        :allow-searching="false"
      />
    </EColumns>
  </EjsGrid>
</template>
